### PR TITLE
Upstream PRs 1228, 1236, 1243, 1238, 1246, 1247, 1242, 1250, 1244, 1241, 1257, 1226, 1252, 1118, 1245, 1266, 1269

### PR DESCRIPTION
**Pull request by jonasnick**
[bitcoin-core/secp256k1#1228]: release cleanup: bump version after 0.3.0
[bitcoin-core/secp256k1#1236]: Update comment for secp256k1_modinv32_inv256
[bitcoin-core/secp256k1#1243]: build: Ensure no optimization when building for coverage analysis
[bitcoin-core/secp256k1#1238]: build: bump CMake minimum requirement to 3.13
[bitcoin-core/secp256k1#1246]: Typo
[bitcoin-core/secp256k1#1247]: Apply Checks only in VERIFY mode.
[bitcoin-core/secp256k1#1242]: Set ARM ASM symbol visibility to `hidden`
[bitcoin-core/secp256k1#1250]: No need to subtract 1 before doing a right shift
[bitcoin-core/secp256k1#1244]: Suppress `-Wunused-parameter` when building for coverage analysis
[bitcoin-core/secp256k1#1241]: build: Improve `SECP_TRY_APPEND_DEFAULT_CFLAGS` macro
[bitcoin-core/secp256k1#1257]: ct: Use volatile "trick" in all fe/scalar cmov implementations
[bitcoin-core/secp256k1#1226]: Add CMake instructions to release process
[bitcoin-core/secp256k1#1252]: Make position of * in pointer declarations in include/ consistent
[bitcoin-core/secp256k1#1118]: Add x-only ecmult_const version with x specified as n/d
[bitcoin-core/secp256k1#1245]: tests: Add Wycheproof ECDSA vectors
[bitcoin-core/secp256k1#1266]: release: Prepare for 0.3.1
[bitcoin-core/secp256k1#1269]: changelog: Fix link

This PR can be recreated with `./contrib/sync-upstream.sh -b sync-upstream range v0.3.1`.
Tip: Use `git show --remerge-diff` to show the changes manually added to the merge commit.

- Made position of `*` consistent in -zkp `include/` files.

### CODE REVIEW

**Comment by real-or-random** [comment]
> Made position of `*` consistent in -zkp `include/` files.

`git grep "[a-zA-Z]\* " include` shows more locations that need to be modified.

**Comment by real-or-random** [comment]
ACK otherwise

**Comment by jonasnick** [comment]
Oops sorry, should be fixed now.
```
❯ git grep "[a-zA-Z]\* " include
include/secp256k1.h: *  This context object offers *only limited functionality* , i.e., it cannot be used
include/secp256k1_surjectionproof.h: *  stack; please *do not* use these internals directly.
include/secp256k1_surjectionproof.h: * This data type is *not* opaque. It will always be 32 bytes of whatever
include/secp256k1_whitelist.h: *  stack; please *do not* use these internals directly. To learn the number
```

**Review by real-or-random — APPROVED** [review]
utACK a9a5c24de2e96ac00b0a3e56f6fd7a81a1b37337

**Review by real-or-random — APPROVED** [review]
ACK a9a5c24de2e96ac00b0a3e56f6fd7a81a1b37337

**Pull request merged**
