### PR TITLE
configure: Clean ups

### PR DESCRIPTION
**Pull request by real-or-random**

### CODE REVIEW

**Comment by jonasnick** [comment]
What is the canonical order of modules?

**Comment by real-or-random** [comment]
The one used for the echos, i.e., first the upstream modules (in their order) and then our modules in the ordered they appeared. And that order should be used in the other places, just sometimes reversed...

Let me add a comment. (I just don't want to add a comment everywhere we list modules. This would again need to be done upstream, and I don't want to make that dance yet another time, at least not for an issue of this kind. :D)

**Comment by real-or-random** [comment]
Updated.

**Comment by real-or-random** [comment]
Changed it again, so that the main idea can at least be ported to upstream easily. Really ready for review now. ^^

**Review by jonasnick — COMMENTED** [review]
ACK 860e3bb29461c05b495c6f027b6c5a62532738b5

**Pull request merged**
