### PR TITLE
Upstream PRs 1314, 1317, 1318, 1316, 1327, 1310, 1328, 1333, 1330, 1334, 1337, 1341, 1339, 1350, 1349, 1338, 1129, 1347, 1336, 1295, 1354, 1355, 1356

### PR DESCRIPTION
**Pull request by jonasnick**
[bitcoin-core/secp256k1#1314]: release cleanup: bump version after 0.3.2
[bitcoin-core/secp256k1#1317]: Make fe_cmov take max of magnitudes
[bitcoin-core/secp256k1#1318]: build: Enable -DVERIFY for precomputation binaries
[bitcoin-core/secp256k1#1316]: Do not invoke fe_is_zero on failed set_b32_limit
[bitcoin-core/secp256k1#1327]: ci: Move wine prefix to /tmp to avoid error D8037 in cl.exe
[bitcoin-core/secp256k1#1310]: Refine release process
[bitcoin-core/secp256k1#1328]: build: Bump MSVC warning level up to W3
[bitcoin-core/secp256k1#1333]: test: Warn if both `VERIFY` and `COVERAGE` are defined
[bitcoin-core/secp256k1#1330]: refactor: take use of `secp256k1_scalar_{zero,one}` constants
[bitcoin-core/secp256k1#1334]: fix input range comment for `secp256k1_fe_add_int`
[bitcoin-core/secp256k1#1337]: ci: Fix error D8037 in `cl.exe` (attempt 2)
[bitcoin-core/secp256k1#1341]: docs: correct `pubkey` param descriptions for `secp256k1_keypair_{xonly_,}pub`
[bitcoin-core/secp256k1#1339]: scalar: refactor: use `secp256k1_{read,write}_be32` helpers
[bitcoin-core/secp256k1#1350]: scalar: introduce and use `secp256k1_{read,write}_be64` helpers
[bitcoin-core/secp256k1#1349]: Normalize ge produced from secp256k1_pubkey_load
[bitcoin-core/secp256k1#1338]: Drop no longer needed `#include "../include/secp256k1.h"`
[bitcoin-core/secp256k1#1129]: ElligatorSwift + integrated x-only DH
[bitcoin-core/secp256k1#1347]: field: Document return value of fe_sqrt()
[bitcoin-core/secp256k1#1336]: Use `__shiftright128` intrinsic in `secp256k1_u128_rshift` on MSVC
[bitcoin-core/secp256k1#1295]: abi: Use dllexport for mingw builds
[bitcoin-core/secp256k1#1354]: Add ellswift to CHANGELOG
[bitcoin-core/secp256k1#1355]: Fix a typo in the error message
[bitcoin-core/secp256k1#1356]: ci: Adjust Docker image to Debian 12 "bookworm"

This PR can be recreated with `./contrib/sync-upstream.sh -b sync-upstream range 799f4eec`.
Tip: Use `git show --remerge-diff` to show the changes manually added to the merge commit.

### CODE REVIEW

**Comment by real-or-random** [comment]
Okay, good news is that CI seems to work now, bad news is that this means all CI failures are real issues... Happy to split up the investigation work. (Probably easier to sync in chat.)

**Comment by real-or-random** [comment]
Should work now, let's see what CI says...

Not sure if https://github.com/BlockstreamResearch/secp256k1-zkp/pull/257/commits/33f86f3aad114103a5a09becba4ad79c43959579 is the nicest fix... I don't like the idea of maintaining MSVC-specific code, but I'm not sure if I have a more elegant solution. MSVC 19.33 is quite recent, and leaving a warning in the build is not nice either. Alternatively, we could pass `-wd4090` to the build (we also pass some other `-wd` options), but the nice thing about the pragma is that it documents that this is fixed in recent compiler version. I think, we want to enable warning 4090; it's just buggy in the case of double pointers. 

Godbolt playground for the warning suppression on MSVC: https://godbolt.org/z/cT15vTfv8

**Comment by real-or-random** [comment]
I restarted two jobs that have failed due to https://github.com/BlockstreamResearch/secp256k1-zkp/pull/248

**Comment by jonasnick** [comment]
> Not sure if https://github.com/BlockstreamResearch/secp256k1-zkp/commit/33f86f3aad114103a5a09becba4ad79c43959579 is the nicest fix...

Probably ok for now. I don't have a better suggestion.

**Pull request merged**
